package zmarkdown.javaeditor.ihm;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.text.Normalizer;
import java.text.Normalizer.Form;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author firm1
 */
public class OnlineContent extends javax.swing.JDialog {

    Map<Integer, Element> mappingTuto;
    /**
     * Creates new form OnlineContent
     */
    public OnlineContent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        mappingTuto = new HashMap<Integer, Element>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultListModel listModel = new DefaultListModel();

        try {
            Document doc = Jsoup.connect("http://zestedesavoir.com/tutoriels/").get();
            Elements tutos = doc.select("article");
            int i = 0;
            for (Element tuto:tutos) {
                String t = tuto.select("div").select("h3").text();
                listModel.add(i, t);
                mappingTuto.put(i, tuto);
                i++;
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        jList1 = new javax.swing.JList(listModel);
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sélectionnez le tutoriel a télécharger");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout(1, 0));

        jButton2.setText("Télécharger");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static final Pattern NONLATIN = Pattern.compile("[^\\w-]");  
    private static final Pattern WHITESPACE = Pattern.compile("[\\s]");

    public String makeSlug(String input) {  
        String nowhitespace = WHITESPACE.matcher(input).replaceAll("-");  
        String normalized = Normalizer.normalize(nowhitespace, Form.NFD);  
        String slug = NONLATIN.matcher(normalized).replaceAll("");  
        return slug.toLowerCase(Locale.ENGLISH);  
    }  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser dialog = new JFileChooser(new File("."));
	dialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	if (dialog.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
	    File file = dialog.getSelectedFile();
            try {
                Element elt = mappingTuto.get(jList1.getSelectedIndex());
                String[] parts = elt.select("a").attr("href").split("/");
                String id = parts[2];
                URL url = new URL("http://zestedesavoir.com/tutoriels/telecharger/?tutoriel="+id+"&online");
                URLConnection conn = url.openConnection();
                InputStream in = conn.getInputStream();
                FileOutputStream out = new FileOutputStream(file.getAbsolutePath() + File.separator + makeSlug(jList1.getSelectedValue().toString())+".zip");
                byte[] b = new byte[1024];
                int count;
                while ((count = in.read(b)) >= 0) {
                    out.write(b, 0, count);
                }
                out.flush(); out.close(); in.close();                   

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Désole, Zest'Editor n'arrive pas à télécharger ce tutoriel", "alert", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this, "Votre tutoriel "+jList1.getSelectedValue().toString()+" a été téléchargé avec succès", "Information", JOptionPane.INFORMATION_MESSAGE);
	}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OnlineContent dialog = new OnlineContent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
